// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWyRCHbeFQqAHLE6364TB1u69HlXKbsP8',
    appId: '1:601870044740:web:8d15217c6e128fbf233611',
    messagingSenderId: '601870044740',
    projectId: 'talknearn-a590f',
    authDomain: 'talknearn-a590f.firebaseapp.com',
    storageBucket: 'talknearn-a590f.firebasestorage.app',
    measurementId: 'G-B7MGJHTKEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OXj5p2BCkTz6NKEgihvSXO97BS6Cn4s',
    appId: '1:601870044740:android:8301402a36c63886233611',
    messagingSenderId: '601870044740',
    projectId: 'talknearn-a590f',
    storageBucket: 'talknearn-a590f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS_jFyfwTRqO_HRpTVSqKCZAgIsI9ym9E',
    appId: '1:601870044740:ios:43ad1a323cd2f57f233611',
    messagingSenderId: '601870044740',
    projectId: 'talknearn-a590f',
    storageBucket: 'talknearn-a590f.firebasestorage.app',
    iosBundleId: 'p',
  );
}
